AppBundle\Entity\Concert:
    type: entity
    table: concert
    indexes:
        concert_FI_1:
            columns:
                - member_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        memberId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: member_id
        city:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        url:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        datetime:
            type: datetime
            nullable: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    lifecycleCallbacks: {  }
