AppBundle\Entity\Folkpost:
    type: entity
    table: folkpost
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        image:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        pdf:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        releaseAt:
            type: date
            nullable: false
            column: release_at
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    lifecycleCallbacks: {  }
