AppBundle\Entity\Genre:
    type: entity
    table: genre
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        nameUrl:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: name_url
        icon:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    lifecycleCallbacks: {  }
