AppBundle\Entity\News:
    type: entity
    table: news
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        subtitle:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        contentShort:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: content_short
        contentLong:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: content_long
        file:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        fileDescription:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: file_description
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    lifecycleCallbacks: {  }
